### ISSUE TITLE
Revisión

### ISSUE THREAD

**Issue by EduardoHernandezGuzman** [4GeeksAcademy/kamelmat-formulario-HTML5#1]
# Revisión - Aprobado :white_check_mark:
- [x] Estilo de código y limpieza
# Feedback
- ¡Buen proyecto @kamelmat  ... ¡Felicidades!
## Estilo de código y limpieza
- ¡Bien hecho!
## Mejores prácticas/comentarios
- Recuerda que Los ID dentro de un documento HTML deben ser únicos. En tu código, los ID `inputPassword4` se repiten varias veces. 
- Intenta dejar los márgenes laterales como en el proyecto original [Aquí](https://storage.googleapis.com/breathecode-asset-images/b1dce6958cdd29b72248a6db2e6450994eedbaeae3f9086b5bc78a30cfa2d15c.png?raw=true)

**Comment by kamelmat** [comment]
### Gracias @EduardoHernandezGuzman !!!🙏🏽

Lo de los **ID** básicamente creo que me quedó de copiar las formulas de bootsrap. Como explico Hector creo que servían para llamar la clase relacionada o algo así, pero me falta entenderlo bien. Miro el `código` para más especificidad al respecto. 

### Tema Margenes
>Voy a mirar lo de los márgenes, entiendo que con poner `margin` al `body` puedo solucionarlo fácil. 
>Creo que asumí que era una diferencia del tamaño de la pantalla con la que se hizo la captura para el ejemplo, >en la mía se ve todo más grande y de hecho creo que le queda algo de scroll.

**Comment by EduardoHernandezGuzman** [comment]
![Captura de pantalla de 2024-03-14 10-56-07](https://github.com/4GeeksAcademy/kamelmat-formulario-HTML5/assets/139759297/045b3bdb-31fd-4d43-8630-a297fee7d38f)
El `id` se tiene que corresponder con el `for` (usar el mismo). Están bien los del recuadro rojo. 
Pero luego en el recuadro verde y amarillo repites el `id`. Deberías usar un `id` diferente. Por ejemplo en los recuadros verdes usar como `id` imputPassword5 y su `for`  imputPassword5 .
Y en los recuadros amarillos usar  como `id` imputPassword6 y su `for`  imputPassword6 .

En cuanto a los márgenes, tienes razón... fallo mío es tema de la captura que han hecho para el ejemplo :smiley::smiley::smiley:

**Comment by kamelmat** [comment]
# Vaaaaaale!
Ahora lo entiendo! Gracias por la explicación. 
Lo corrijo🙏🏽

**Comment by EduardoHernandezGuzman** [comment]
Muy buen trabajo @kamelmat :clap::clap::clap:
